### ISSUE TITLE
Adjust other Speakers/Audio Devices volume

### ISSUE THREAD

**Issue by Jiroretardo** [PcVolumeControl/PcVolumeControliOS#11]
Allow to change the app volumes that are in other speakers and audio devices.

So there's more choices of changing volumes coming from different speakers.

**Comment by cwbooth5** [comment]
The app has a little bar where you can select the current audio output device, like a pair of headphones or your PC speakers. You can only be on one at a time. Did you mean you want to be able to set different volume levels so when you switch around between these various audio outputs, the settings are unique per audio device?
